export const MOVIE_TRAILER_FETCH_START = 'MOVIE_TRAILER_FETCH/START';
export const MOVIE_TRAILER_FETCH_FAILURE = 'MOVIE_TRAILER_FETCH/FAILED';
export const MOVIE_TRAILER_FETCH_SUCCESS = 'MOVIE_TRAILER_FETCH/SUCCESS'
export const MOVIE_TRAILER_FETCH_RESET = 'MOVIE_TRAILER_FETCH/RESET'