export const MOVIE_SEARCH_START = 'MOVIE_SEARCH/START';
export const MOVIE_SEARCH_FAILURE = 'MOVIE_SEARCH/FAILED';
export const MOVIE_SEARCH_SUCCESS = 'MOVIE_SEARCH/SUCCESS'
export const MOVIE_SEARCH_RESET = 'MOVIE_SEARCH/RESET'

export const SEARCH_TEXT_SET = 'SEARCH_TEXT/SET'